create sequence hibernate_sequence start with 1 increment by 1
create table link (id integer not null, expire timestamp, path varchar(3) not null, url varchar(120) not null, oper_id integer not null, primary key (id))
create table oper (id integer generated by default as identity, email varchar(128), login varchar(32) not null, name varchar(75), password varchar(16) not null, primary key (id))
create table oper_role (oper_id integer not null, roles varchar(8))
alter table link add constraint UK_i3jxn290kwqifmhc7imx3ifrg unique (path)
alter table link add constraint UK_4dycbe6q8trcendnql3b13cuf unique (url)
alter table oper add constraint UK_qlhurh7b8ia5tvxlp90w7ct42 unique (login)
alter table link add constraint FKqsglvq78coi7t1q4sext9bahb foreign key (oper_id) references oper
alter table oper_role add constraint FK1jingjob57g9enj2tlsx22ymp foreign key (oper_id) references oper


